import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer/Footer";
import Header from "./Components/Header/HeaderUp/Header";
import styles from './layout.module.scss'
import Subscribe from "./Components/Subscribe/Subscribe";
import HeaderDown from "./Components/Header/HeaderDown";
import Menu from "./Components/Menu/Menu";
import Image from "next/image";
import RecoilWrapper from "./RecoilWrapper/RecoilWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={styles.container}>
      <body className={inter.className}>
        <div className={styles.header}>
          <Header color={""} />
        </div>
        <div className={styles.headDown}>
        <HeaderDown />
        </div>
        <Menu src={"blackcall.svg"} />
        <Image src={'categories-background.svg'} alt="image" width={1920} height={120} className={styles.img} />
        <RecoilWrapper>
        {children}
        </RecoilWrapper>
        <Subscribe />
        <Footer />
      </body>
    </html>
  );
}
